ba_web_app/ai_experiments/views.py
# -*- coding: utf-8 -*-
"""AiExperiment views."""
import datetime
import hashlib
import json
import os
import uuid
import zipfile
from io import BytesIO

import pandas as pd
from flask import Blueprint, current_app, render_template, request, send_file, flash, redirect
from sqlalchemy import desc
from werkzeug.utils import secure_filename

from ba_web_app.ai_experiments.forms import SubmitAiExperimentForm
from ba_web_app.ai_experiments.models import AiExperiment, AiFileUpload, AiGeneAlias
from ba_web_app.ai_utils.client import submit_experiment

blueprint = Blueprint(
    "ai_experiments", __name__, url_prefix="/ai_experiments", static_folder="../static"
)

@blueprint.route("/")
def index():
    """AI Experiment home page."""
    ai_experiments = AiExperiment.query.order_by(desc(AiExperiment.created_at)).order_by(desc(AiExperiment.id)).all()
    return render_template("ai_experiments/index.html", ai_experiments=ai_experiments)

@blueprint.route("/new/")
def create():
    """Submit a AI Experiment."""
    # config = read_config("/tmp/biocurator-assistant/config.cfg")
    form = SubmitAiExperimentForm(request.form)
    return render_template("ai_experiments/submit.html", form=form)

@blueprint.route("/view/<int:ai_experiment_id>/")
def view(ai_experiment_id):
    """View a AI Experiment."""
    ai_experiment = AiExperiment.query.get(ai_experiment_id)
    responses = get_ai_responses(ai_experiment)
    csv_responses = convert_ai_responses_to_csv(responses)

    return render_template("ai_experiments/view.html", ai_experiment=ai_experiment, ai_responses=responses, csv_responses=csv_responses)

@blueprint.route("/submit/", methods=["POST"])
def submit():
    """Handle submitted a AI Experiment."""
    form = SubmitAiExperimentForm(request.form)

    # check if the post request has the file part
    if 'pdfFiles' not in request.files:
        flash('No file part')
        return redirect(request.url)

    flask_app = current_app._get_current_object()

    # log the form data
    print(form.assistant.data)

    # The experiment group ID is used to group multiple experiments together
    # Use a UUID or similar to group experiments together
    experiment_group_id = uuid.uuid4().hex

    if not form.validate_on_submit():
        flash("Invalid form data")
        return render_template("ai_experiments/submit.html", form=form)

    # The files that were uploaded with the form as "pdfFiles"
    uploaded_pdf_files = request.files.getlist("pdfFiles")

    ai_experiment = None
    if form.save_files_separately:
        print("Saving each file as a separate experiment")
        for file in uploaded_pdf_files:
            ai_experiment = process_experiment(experiment_group_id, flask_app, form, [file])
    else:
        print("Saving all files as a single experiment")
        ai_experiment = process_experiment(experiment_group_id, flask_app, form, uploaded_pdf_files)

    return render_template("ai_experiments/submitted.html", ai_experiment=ai_experiment)


def process_experiment(experiment_group_id, flask_app, form, uploaded_pdf_files):
    # Save the AI Experiment to the database
    ai_experiment = AiExperiment.create(
        group_id=experiment_group_id,
        name=form.name.data,
        assistant=form.assistant.data,
        prompt=form.prompt.data,
        functions=form.functions.data,
    )
    # Save the uploaded files to the database as AiFileUpload objects
    ai_file_uploads = []
    for file in uploaded_pdf_files:
        if file and file.filename != "":
            filename = secure_filename(file.filename)
            file_without_extension, file_extension = os.path.splitext(filename)

            # does it already exist?
            persisted_filename = os.path.join(flask_app.config["UPLOAD_FOLDER"], filename)
            uploaded_file_hash = hash_file(file)

            while os.path.exists(persisted_filename):
                # Is the existing file the same as the uploaded file?
                with open(persisted_filename, 'rb') as f:
                    persisted_file_hash = hashlib.sha256(f.read()).hexdigest()
                if uploaded_file_hash == persisted_file_hash:
                    print(f"File already exists with same name and contents: {filename}")
                    break
                timestamp = str(datetime.datetime.now().timestamp()).replace(".", "")
                filename_with_timestamp = file_without_extension + "_" + timestamp + file_extension
                persisted_filename = os.path.join(flask_app.config["UPLOAD_FOLDER"], filename_with_timestamp)

            file.save(persisted_filename)
            print("file.filename")
            print(file.filename)
            print("persisted_filename")
            print(persisted_filename)
            ai_file_uploads.append(
                AiFileUpload.create(
                    filename=file.filename,
                    filepath=persisted_filename,
                    file_type="pdf",
                    ai_experiment_id=ai_experiment.id,
                )
            )
    filepaths = [f.filepath for f in ai_file_uploads]
    submit_experiment(api_key=flask_app.config["OPENAI_API_KEY"],
                      assistant_instructions=ai_experiment.assistant,
                      prompt=ai_experiment.prompt,
                      functions=ai_experiment.functions,
                      files=filepaths,
                      unique_id=str(ai_experiment.id))
    return ai_experiment

@blueprint.route("/group_download/<string:ai_experiment_group_id>/")
def group_download(ai_experiment_group_id):
    """Download a group of AI Experiments."""
    ai_experiments = AiExperiment.query.filter_by(group_id=ai_experiment_group_id).all()

    #create a zip file with a subdirectory for each experiment
    memory_file = BytesIO()
    with zipfile.ZipFile(memory_file, 'w', zipfile.ZIP_DEFLATED) as zf:
        for ai_experiment in ai_experiments:
            files = get_file_contents_for_experiment(ai_experiment)

            # Create a subdirectory for the experiment
            experiment_dir = f"experiment_{ai_experiment.id}/"

            for file in files:
                filepath = experiment_dir + file["filename"]
                zf.writestr(filepath, file["content"])

    memory_file.seek(0)
    return send_file(memory_file, download_name=f"ai_experiment_group_{ai_experiment_group_id}.zip", as_attachment=True)



@blueprint.route("/group_summary/<string:ai_experiment_group_id>/")
def group_summary(ai_experiment_group_id):
    """Download a summary of AI Experiments."""
    ai_experiments = AiExperiment.query.filter_by(group_id=ai_experiment_group_id).all()

    # Create a DataFrame to store the data
    data = []

    # Write the headers
    headers = ["Experiment ID", "Filename", "Gene", "Status", "Result", "Details", "Current Gene"]

    for ai_experiment in ai_experiments:
        responses = get_ai_responses(ai_experiment)
        csv_responses = convert_ai_responses_to_csv(responses, include_header=False)
        print("Getting gene experiment result for experiment", ai_experiment.id)
        ai_gene_experiment_result = ai_experiment.gene_experiment_result

        for filename, content in csv_responses.items():
            found_genes = content.split("\n")
            distinct_genes = set(found_genes)
            for row in distinct_genes:
                row = row.strip().lower()
                indexed = ""
                result_column = ""
                current_gene = ""
                true_positives = ai_gene_experiment_result.true_positives.split("\n") if ai_gene_experiment_result else []
                true_positives = list(map(str.strip, true_positives))
                true_positives = [x.lower() for x in true_positives]
                if row in true_positives:
                    indexed = "Indexed"
                    result_column = "True positive"
                    current_gene = row
                else:
                    #check for alias
                    alias_match = AiGeneAlias.query.filter_by(alias=row).first()
                    if alias_match:
                        alias_gene = alias_match.gene
                        current_gene = alias_gene
                        if alias_gene.lower() in true_positives:
                            indexed = "Indexed"
                            result_column = "true positive -symbol mismatch"

                data.append([ai_experiment.id, filename, row, indexed, result_column, "", current_gene])

    # Create a DataFrame from the data
    df = pd.DataFrame(data, columns=headers)

    # sort the DataFrame by Experiment ID, then by Gene
    df = df.sort_values(by=["Experiment ID", "Gene"])

    # Save the DataFrame to a BytesIO object as an Excel file
    output = BytesIO()
    with pd.ExcelWriter(output, engine='xlsxwriter') as writer:
        # Write the summary sheet
        df.to_excel(writer, index=False, sheet_name='Summary')

        # Get the workbook and worksheet objects
        workbook  = writer.book
        summary_sheet = writer.sheets['Summary']

        # Adjust the column widths in the summary sheet
        for i, column in enumerate(df.columns):
            column_length = max(df[column].astype(str).map(len).max(), len(column)) + 2
            summary_sheet.set_column(i, i, column_length)

        # Write the second sheet
        details_sheet = workbook.add_worksheet('config')
        first_experiment = ai_experiments[0]
        details = [
            ("Experiment Name", first_experiment.name),
            ("Assistant", first_experiment.assistant),
            ("Prompt", first_experiment.prompt),
            ("Functions", first_experiment.functions)
        ]

        for row_idx, (header, value) in enumerate(details):
            details_sheet.write(row_idx, 0, header)
            details_sheet.write(row_idx, 1, value)

        # Adjust the column widths in the config sheet
        for col_idx, _ in enumerate(details[0]):

ba_web_app/ai_gene_experiment_results/views.py
# -*- coding: utf-8 -*-
"""AiExperiment views."""
import csv
import io

from flask import Blueprint, render_template, request

from ba_web_app.ai_experiments.models import AiExperiment, AiGeneExperimentResult, AiGeneAlias
from ba_web_app.ai_experiments.views import get_ai_responses, convert_ai_responses_to_csv

blueprint = Blueprint(
    "ai_gene_experiment_results", __name__, url_prefix="/ai_gene_experiment_results", static_folder="../static"
)


@blueprint.route("/view/<int:ai_experiment_id>/")
def view(ai_experiment_id):
    # config = read_config("/tmp/biocurator-assistant/config.cfg")
    ai_experiment = AiExperiment.query.get(ai_experiment_id)
    ai_gene_experiment_result = ai_experiment.gene_experiment_result

    return render_template("ai_gene_experiment_results/view.html", ai_gene_experiment_result=ai_gene_experiment_result, ai_experiment=ai_experiment)


@blueprint.route("/create/<int:ai_experiment_id>/")
def create(ai_experiment_id):
    # config = read_config("/tmp/biocurator-assistant/config.cfg")
    ai_experiment = AiExperiment.query.get(ai_experiment_id)
    publication_name = get_pub_name_for_experiment(ai_experiment)
    # ai_gene_experiment_result = AiGeneExperimentResult(ai_experiment_id=ai_experiment_id, publication_name=publication_name)

    return render_template("ai_gene_experiment_results/create.html", form=request.form, publication_name=publication_name, ai_experiment_id=ai_experiment_id)

@blueprint.route("/import/", methods=["GET"])
def import_true_positives():
    return render_template("ai_gene_experiment_results/import.html", form=request.form)

@blueprint.route("/import/", methods=["POST"])
def import_true_positives_post():
    true_positives = request.form["true_positives"].strip()
    rows = []
    for row in true_positives.strip().split("\n"):
        id, pos = row.split(",")
        rows.append({"id": id, "pos": pos})

    grouped_rows = {}
    for row in rows:
        id = row["id"]
        pos = row["pos"]
        if id not in grouped_rows:
            grouped_rows[id] = []
        grouped_rows[id].append(pos)

    transformed_to_csv = {}
    for id, pos in grouped_rows.items():
        transformed_to_csv[id] = "\n".join(pos)

    for id, pos in transformed_to_csv.items():
        print(f"Importing true positives:\n {id}: {pos}")
        ai_experiment = AiExperiment.query.get(id)
        save_ai_gene_experiment_result(ai_experiment.id, None, pos)

    return render_template("ai_gene_experiment_results/imported.html", form=request.form)\

@blueprint.route("/pub_import/<string:ai_experiment_group_id>", methods=["GET"])
def import_pub_true_positives(ai_experiment_group_id):
    return render_template("ai_gene_experiment_results/pub_tp_import.html", form=request.form, ai_experiment_group_id=ai_experiment_group_id)

@blueprint.route("/pub_import/<string:ai_experiment_group_id>", methods=["POST"])
def import_pub_true_positives_post(ai_experiment_group_id):
    true_positives_by_pub = {}
    true_positives = request.form["true_positives"].strip()
    for row in true_positives.strip().split("\n"):
        id, pos = row.split(",")
        if id not in true_positives_by_pub:
            true_positives_by_pub[id] = []
        true_positives_by_pub[id].append(pos.strip())

    true_positives_by_experiment_id = {}
    experiments = AiExperiment.query.filter_by(group_id=ai_experiment_group_id).all()
    for experiment in experiments:
        #get pub_id for this experiment (based on uploads)
        pub_filename = experiment.file_uploads[0].filename
        pub_id = pub_filename.replace(".pdf", "")
        if pub_id in true_positives_by_pub:
            true_positives_by_experiment_id[experiment.id] = true_positives_by_pub[pub_id]

    for experiment_id, pos in true_positives_by_experiment_id.items():
        pos_string = "\n".join(pos)
        print(f"Importing true positives:\n {experiment_id}: {pos_string}")
        save_ai_gene_experiment_result(experiment_id, None, pos_string)

    return render_template("ai_gene_experiment_results/imported.html", form=request.form, ai_experiment_group_id=ai_experiment_group_id)


@blueprint.route("/alias_import/", methods=["GET"])
def import_aliases():
    return render_template("ai_gene_experiment_results/alias_import.html", form=request.form)

@blueprint.route("/alias_import/", methods=["POST"])
def import_aliases_post():
    aliases = request.form["aliases"].strip()
    rows = []
    for row in aliases.strip().split("\n"):
        row = row.strip()
        gene, alias = row.split(",")

        # Check if gene exists
        existing = AiGeneAlias.query.filter_by(gene=gene, alias=alias).first()
        if existing:
            continue

        AiGeneAlias(gene=gene, alias=alias).save()

    return render_template("ai_gene_experiment_results/imported.html", form=request.form)

@blueprint.route("/submit/", methods=["POST"])
def submit():
    # config = read_config("/tmp/biocurator-assistant/config.cfg")
    ai_experiment_id = request.form["ai_experiment_id"]
    publication_name = request.form["publication_name"]
    true_positives = request.form["true_positives"].strip()

    save_ai_gene_experiment_result(ai_experiment_id, publication_name, true_positives)

    return render_template("ai_gene_experiment_results/submitted.html", form=request.form)


def save_ai_gene_experiment_result(ai_experiment_id, publication_name, true_positives):
    ai_experiment = AiExperiment.query.get(ai_experiment_id)
    if not publication_name:
        publication_name = get_pub_name_for_experiment(ai_experiment)
    responses = get_ai_responses(ai_experiment)
    responses_csv = convert_ai_responses_to_csv(responses, include_header=False)
    existing_result = ai_experiment.gene_experiment_result
    if existing_result:
        print("Deleting existing result")
        existing_result.delete()
    output = io.StringIO()
    csv_writer = csv.writer(output)
    for filename, content in responses_csv.items():
        for row in content.split("\n"):
            csv_writer.writerow([row])
    csv_string = output.getvalue()
    output.close()
    ai_gene_experiment_result = AiGeneExperimentResult(ai_experiment_id=ai_experiment_id,
                                                       publication_name=publication_name,
                                                       true_positives=true_positives,
                                                       # responses=json.dumps(responses),
                                                       responses_csv=csv_string)
    ai_gene_experiment_result.save()
    # ai_gene_experiment_result.save()
    print("ai_gene_experiment_result: ", publication_name)


def get_pub_name_for_experiment(ai_experiment):
    uploads = ai_experiment.file_uploads
    first_upload = uploads[0]
    publication_name = first_upload.filename
    return publication_name

ba_web_app/templates/ai_experiments/group.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
  <h1 class="mt-5">Experiments for Group #{{ ai_experiment_group_id }}</h1>
    <p>
        <a href="{{ url_for('ai_experiments.group_download', ai_experiment_group_id=ai_experiment_group_id) }}" class="btn btn-primary">Download All</a>
        <a href="{{ url_for('ai_experiments.group_summary', ai_experiment_group_id=ai_experiment_group_id) }}" class="btn btn-primary">Group Summary</a>
    </p>
{%  for experiment in ai_experiments %}
    <div class="card mt-3">
        <div class="card-body">
            <h5 class="card-title">{{ experiment.name }}</h5>
            <a href="{{ url_for('ai_experiments.view', ai_experiment_id=experiment.id) }}" class="btn btn-primary">View</a>
        </div>
    </div>
{% endfor %}

</div>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
{% endblock %}

{% block js %}
    <script src="{{ url_for('static', filename='js/copy.js') }}"></script>
{% endblock %}

ba_web_app/templates/ai_experiments/index.html
{% extends "layout.html" %}
{% block content %}
    <div class="container">
        <h1 class="mt-5">List of Experiments</h1>
        <br/>
        <a href="/ai_experiments/new" class="btn btn-primary">Create New</a>
        <br/>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Created At</th>
                    <th>Download</th>
                </tr>
            </thead>
            <tbody>
                {% for experiment in ai_experiments %}
                    <tr>
                        <td><a href="/ai_experiments/view/{{ experiment.id }}">{{ experiment.id }}</a></td>
                        <td>{{ experiment.name }}</td>
                        <td>{{ experiment.created_at.strftime('%Y-%m-%d %H:%M:%S') }}</td>
                        <td><a href="{{ url_for('ai_experiments.downloads', ai_experiment_id=experiment.id) }}">Download</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <a href="/ai_experiments/new" class="btn btn-primary">Create New</a>
    </div>

{% endblock %}

ba_web_app/templates/ai_experiments/submit.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
  <h1 class="mt-5">Submit</h1>
    <br/>
    <form id="submitAiExperimentForm" class="form" method="POST" action="/ai_experiments/submit" enctype="multipart/form-data" role="form">
           {{ form.csrf_token }}
            <div class="form-group">
                {{form.name.label}}
                {{form.name(placeholder="Experiment Name", class_="form-control")}}
            </div>
            <div class="form-group mt-3">
                {{form.assistant.label}}
                {{form.assistant(placeholder="Assistant", class_="form-control", rows="10")}}
            </div>
            <div class="form-group mt-3">
                {{form.prompt.label}}
                {{form.prompt(placeholder="Prompt", class_="form-control", rows="10")}}
            </div>
            <div class="form-group mt-3">
                {{form.functions.label}}
                {{form.functions(placeholder="Functions", class_="form-control", rows="10")}}
            </div>
            <div class="form-group mt-3 mb-3">
                <label for="pdfFiles">Upload PDF(s)</label>
                <input type="file" class="form-control" name="pdfFiles" multiple>
            </div>

{#          form.save_files_separately boolean value checkbox #}
            <div class="form-group mt-3 mb-3">
                <input type="checkbox" name="saveFilesSeparately" id="saveFilesSeparately">
                <label for="saveFilesSeparately">Save Files Separately as Their Own Experiment</label>
            </div>

            <p><input class="btn btn-primary" type="submit" value="Submit"></p>
    </form>
</div>
{% endblock %}

ba_web_app/templates/ai_experiments/submitted.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
  <h1 class="mt-5">Submitted</h1>
    <br/>
    <p>Thank you for submitting.</p>
    <p>Successfully created experiment with ID# {{ ai_experiment.id }}</p>
    <a href="{{ url_for('ai_experiments.view', ai_experiment_id=ai_experiment.id) }}" class="btn btn-primary">View</a>
    <br/>
    <div class="mt-3">
    <a href="{{ url_for('ai_experiments.index') }}" class="btn btn-primary">Back to Experiments</a>
    <a href="{{ url_for('ai_experiments.create') }}" class="btn btn-primary">Submit another</a>
    <a href="{{ url_for('ai_experiments.clone', ai_experiment_id=ai_experiment.id) }}" class="btn btn-primary">Clone</a>
    </div>
</div>
{% endblock %}

ba_web_app/templates/ai_experiments/view.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
  <h1 class="mt-5">Experiment #{{ ai_experiment.id }} : {{ ai_experiment.name }}</h1>
    <h2>Artifacts</h2>
    <div>
        <a href="{{ url_for('ai_experiments.downloads', ai_experiment_id=ai_experiment.id) }}">Download</a>

        <a href="{{ url_for('ai_gene_experiment_results.view', ai_experiment_id=ai_experiment.id) }}">Gene Experiment Results</a>
    </div>
    <br/>
    {% if ai_experiment.group_id %}
        <h2>Group</h2>
        <div>
            <a href="{{ url_for('ai_experiments.group', ai_experiment_group_id=ai_experiment.group_id) }}">{{ ai_experiment.group_id }}</a>
        </div>
        <br/>
    {% endif %}

    <h2>Responses</h2>
    <div>
        {% for key, response in ai_responses.items() %}
            <h5>{{ key }}</h5>
            <button type="button" class="btn btn-secondary mb-3 copy-pre">Copy</button>
            <pre>{{ response }}</pre>
        {% endfor %}
    </div>

    <h2>Responses as CSV</h2>
    <div>
        {% for key, response in csv_responses.items() %}
            <h5>{{ key }}</h5>
            <button type="button" class="btn btn-secondary mb-3 copy-pre">Copy</button>
            <pre>{{ response }}</pre>
        {% endfor %}
    </div>

    <h2>Assistant Definition</h2>
    <div>
        <button type="button" class="btn btn-secondary mb-3 copy-pre">Copy</button>
        <pre>{{ ai_experiment.assistant }}</pre>
    </div>

    <br/>
    <h2>Prompt</h2>
    <div>
        <button type="button" class="btn btn-secondary mb-3 copy-pre">Copy</button>
        <pre>{{ ai_experiment.prompt }}</pre>
    </div>

    <br/>
    <h2>Functions</h2>
    <div>
        <button type="button" class="btn btn-secondary mb-3 copy-pre">Copy</button>
        <pre>{{ ai_experiment.functions }}</pre>
    </div>

    <br/>
    <div>
        <a href="{{ url_for('ai_experiments.clone', ai_experiment_id=ai_experiment.id) }}" type="button" class="btn btn-secondary mb-3">Create New Experiment As Clone</a>
        <a href="{{ url_for('ai_gene_experiment_results.create', ai_experiment_id=ai_experiment.id) }}" type="button" class="btn btn-secondary mb-3">Capture Gene Experiment Results</a>
    </div>
</div>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
{% endblock %}

{% block js %}
    <script src="{{ url_for('static', filename='js/copy.js') }}"></script>
{% endblock %}